version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
  
artifacts:
  files:
    - target/messageUtil-1.0.jar

batch:
  fast-fail: false
  build-graph:
    - identifier: build1
      ignore-failure: false

    - identifier: build2
      ignore-failure: false
      
    - identifier: build3
      ignore-failure: false

reports:
  codebuild-demo-report:
    files:
      - '**/*'
    base-directory: src/test/java
    discard-paths: false
